### default
GET http://localhost:4000/
### default
GET http://localhost:4000/hostname
### expect return OK with 200
GET http://localhost:4000/ext/http

### expect return KO with 404
GET http://localhost:4000/ext/ex

### expect return OK with 200
GET http://localhost:4000/filename/main.go

### expect return KO with 404
GET http://localhost:4000/filename/gos.um

### expect return OK with 200
GET http://localhost:4000/contain/feph

### expect return KO with 404
GET http://localhost:4000/contain/mode

### expect return OK with erroer endpoint
GET http://localhost:4000/contin/mode

### expect return OK with erroer endpoint
POST http://localhost:4000/contin/mode

{
    "test" : "test"
}

### expect return OK with erroer endpoint
PUT http://localhost:4000/contin/mode
### expect return OK with erroer endpoint
DELETE http://localhost:4000/contin/mode

### 
GET http://localhost:4000/helloGet

### 
GET http://localhost:4000/text
### 
GET http://localhost:4000/con/test
###
POST http://localhost:4000/helloPost
Content-Type: application/json

{
    "test" : "test"
}

###
POST http://localhost:4000/helloPostList
Content-Type: application/json

{
    "test" : "test"
}

### 
GET http://localhost:4000/test